### ISSUE TITLE
Install without master

### ISSUE THREAD

**Issue by Unknown-0** [iTALC/italc#102]
Hello,
I have already seen de issue #88  but i don't known how to create the nex installer with the italc.nsi.in.
Can you explain me how i can complile the installer. When i try i have the error : 
"Error in macro MUI_PAGE_LICENSE on macroline 21
Error in script "C:\Users\Robin\Downloads\italc-master\nsis\iTALC.nsi.in" on line 65 -- aborting creation process"
Thanks for your help.

**Comment by tobydox** [comment]
I suggest using the official installers. The public alpha release (very soon!) of iTALC/Veyon 4 will contain the features described in #88.

**Comment by Unknown-0** [comment]
Thanks for your reply. I will wait for the release of the V4
