### ISSUE TITLE
Start italc with different port number

### ISSUE THREAD

**Issue by geertverbeke** [iTALC/italc#104]
Hi,
I am trying to install italc on a Windows multiseat computer. Earlier with italc version 1.0.x i can start several italc ica.exe sessions by: ica.exe -ivsport 4001 -isdport 5901 , but with version 3.0.x it doesn't work anymore. 
Only one computer starts up italc with a service i think. 
normal on the client i do such like: 
 ica.exe -ivsport 4001 -isdport 5901  (for workstation 1)
 ica.exe -ivsport 4002 -isdport 5902  (for workstation 2)
 ica.exe -ivsport 4003 -isdport 5903  (for workstation 3)
...
on the master computer i add the workstations with:
IP-ADRESS of computername:4001
IP-ADRESS of computername:4002
IP-ADRESS of computername:4003
...
It was working with Italc version 1.0.x, but for now with the new Windows 10 updates it don't works anymore. 

So i try to install version 3, i can only see one screen of the multiseat (without a portname):
on the master computer i add the workstations with:
IP-ADRESS of computername   -> without   :4001 or :4002  
i think the ica.exe is not started in these other ports and only on the normal standard port (as service)

1. can i start up ica.exe as service on the client with a other port on each workstation?
2. can i start ica.exe manualy on each workstation with a script?

Thanks i advance
Geert Verbeke
ICT

**Comment by tobydox** [comment]
Currently this is not supported any longer however feel free to open an issue for Veyon, the successor of iTALC: https://github.com/veyon/veyon/issues
