### ISSUE TITLE
Silent Installation

### ISSUE THREAD

**Issue by Avaryan** [iTALC/italc#105]
Hello,

What are the best steps for installing the iTalc service and settings remotely? I tried before on an older version, but it didn't work right.

**Comment by tobydox** [comment]
With Veyon as the successor of iTALC there are more options for silent installation including automatic configuration, see https://github.com/veyon/documentation/blob/master/Installation/SilentInstallationOnWindows.md for details. However the "/S" switch should work with current iTALC releases as well.
