### ISSUE TITLE
Auto view issue

### ISSUE THREAD

**Issue by alsho** [iTALC/italc#106]
Hi!

When I click the auto-display button on the master, it automatically organizes all preview clients and blocks the layout (It's OK). But even if I click the button again and release it I can not rearrange the clients anymore, remaining the layout locked.
This issue have a solution? Already uninstalled application, reinstalled, but without success.
It's occurred on iTALC 3.0.3.0 x64 on windows 7 Professional.

**Comment by tobydox** [comment]
Please note that iTALC is not going to be developed any further. Please migrate to the successor product "Veyon" at http://veyon.io which has a completely new master user interface which should also resolve your issue.
