### ISSUE TITLE
3.0.3 Not responding

### ISSUE THREAD

**Issue by eweisner** [iTALC/italc#107]
I have 3.0.3 across 31 computers in my lab.  One Teacher PC and 30 student pc's.  Previously I had my pc on 2.10 (I think) and theirs was on a previous version of 3 (again I think).  We updated all pc's to 3.0.3 and now I can only see a few of the student pc's.  I get a Host Unreachable under the monitor image.  I have permissions on all machines.

Any ideas?

**Comment by ldlx** [comment]
Maybe the public key on the student's computers and the private key on the teacher's computer don't match? Are you sure you are using the key in the teacher role?

**Comment by tobydox** [comment]
Please migrate to Veyon (http://veyon.io) and refer to the troubleshooting chapter in the administrator manual in case of problems :-)
