### ISSUE TITLE
Silent Instalation

### ISSUE THREAD

**Issue by legoulart** [iTALC/italc#108]
Hey, I'm in trouble when trying to run a silent instalation to iTalc (student version).
When I try to run imc or ica from cmd/batch-file i got the following messages:

![error](https://user-images.githubusercontent.com/13538285/28128790-57e1b7b2-6707-11e7-81d4-30c712f910ce.png)

Can anyone help?

**Comment by ldlx** [comment]
Please have a look at the installation directory. There should be Qt5Core.dll, Qt5Gui.dll, Qt5Network.dll, Qt5Widgets.dll and Qt5Xml.dll. In the "platforms"-subdir should be qminimal.dll and qwindows.dll. The DLLs are platform specific (x86/x64).

**Comment by tobydox** [comment]
Please migrate to Veyon (http://veyon.io) and have a look at the administration manual which describes how to perform silent installations :-)
