### ISSUE TITLE
Do not see the mouse cursor

### ISSUE THREAD

**Issue by pcarrey** [iTALC/italc#109]
Hello,

When I take remote control of computer, I don't see the mouse cursor. There is a parameters to configurate ?

Thanks you in advance for your answer
Regards
pcarrey

**Comment by tobydox** [comment]
Hi,

please switch to Veyon (http://veyon.io) which is the official successor of iTALC and has a completely rewritten core. Probably your issue will be fixed already :-)

Best regards

Tobias
