### ISSUE TITLE
Move on Qt5

### ISSUE THREAD

**Issue by SergeyDjam** [iTALC/italc#12]
Hello. Do you plan to project transfer to Qt5?

**Comment by tobydox** [comment]
Thanks for the feedback. This was planned for quite a while and I finally managed to realize it. See latest updates in italc2 branch.

**Comment by spaceone** [comment]
https://github.com/iTALC/italc/tree/qt5

**Comment by SergeyDjam** [comment]
Big phanks

**Comment by SergeyDjam** [comment]
Oh. This no build

In file included from /usr/include/qt5/QtCore/qtextstream.h:40:0,
                 from /usr/include/qt5/QtCore/qdebug.h:42,
                 from /usr/include/qt5/QtCore/QDebug:1,
                 from /home/admin/rpmbuild/BUILD/italc-qt5/lib/src/LogonAuthentication.cpp:26:
/usr/include/qt5/QtCore/qlocale.h:1017:28: note: QDataStream& operator>>(QDataStream&, QLocale&)
 Q_CORE_EXPORT QDataStream &operator>>(QDataStream &, QLocale &);
                            ^
/usr/include/qt5/QtCore/qlocale.h:1017:28: note:   no known conversion for argument 2 from 'Ipc::CommandArgs {aka QMap<QString, QVariant>}' to 'QLocale&'
In file included from /usr/include/qt5/QtCore/qdebug.h:42:0,
                 from /usr/include/qt5/QtCore/QDebug:1,
                 from /home/admin/rpmbuild/BUILD/italc-qt5/lib/src/LogonAuthentication.cpp:26:
/usr/include/qt5/QtCore/qtextstream.h:220:21: note: QTextStream& operator>>(QTextStream&, QTextStreamFunction)
 inline QTextStream &operator>>(QTextStream &s, QTextStreamFunction f)
                     ^
/usr/include/qt5/QtCore/qtextstream.h:220:21: note:   no known conversion for argument 1 from 'QDataStream' to 'QTextStream&'
/home/admin/rpmbuild/BUILD/italc-qt5/lib/src/LogonAuthentication.cpp: In static member function 'static bool LogonAuthentication::authenticateUser(const AuthenticationCredentials&)':
/home/admin/rpmbuild/BUILD/italc-qt5/lib/src/LogonAuthentication.cpp:59:16: error: variable 'QDataStream ds' has initializer but incomplete type
  QDataStream ds( &p );
                ^
lib/CMakeFiles/ItalcCore.dir/build.make:303: recipe for target 'lib/CMakeFiles/ItalcCore.dir/src/LogonAuthentication.o' failed
make[2]: *** [lib/CMakeFiles/ItalcCore.dir/src/LogonAuthentication.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1729: recipe for target 'lib/CMakeFiles/ItalcCore.dir/all' failed
make[1]: *** [lib/CMakeFiles/ItalcCore.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
error: Неверный код возврата из /var/tmp/rpm-tmp.19693 (%build)

:(
