### ISSUE TITLE
Problems with the roles

### ISSUE THREAD

**Issue by barteekelder** [iTALC/italc#22]
Hi, 

It seems I can't use any of the other roles than the teacher role. I've been searching if there are other people with the same problem and there is. There was this guy in 2011 who found it was a bug https://sourceforge.net/p/italc/bugs/226/

It would be great if this is getting fixed soon after all these years. 
We got iTALC running in a few classrooms now and now we really like to be able to have all the teacher computers in a lab in our office. But with a teacher role trying to see or control another teacher role doens't work.

**Comment by tobydox** [comment]
Thank you for your bug report! The whole concept of user roles will be replaced by a more generic approach (user-defined access control rules across all platforms) in iTALC 4 (which is going to be released in Q2/2017). For this reason I can't spend any time in debugging this deprecated feature, I'm sorry..
