### ISSUE TITLE
iTALC Help and Bugs

### ISSUE THREAD

**Issue by joeknex** [iTALC/italc#26]
Hello, In our school we have installed iTALC on over 300 computers and have found some problems and would like to know if any fixes are known (We are using Windows 7 and iTALC 2.0.2)...
1. The "Lock Student" button does nothing... the students can still move their mouse and use the keyboard.

2a. The "Lock All" icons do not get removed from the master client when the button is removed again.
2b. The computer does not remember the "Lock All" if it is logged off and no again. Some students are just doing this and bypassing the system and purpose...
1. Master Clients crash 2-3 times every hour or more.
2. What is the differences of the "Your Role" section? And is their a way to change the "message from Teacher" message to the teacher's name? 
3. Do you know when a new Windows Build will be released?

Thank you in advance :) 

Joe

**Comment by spaceone** [comment]
Do you use iTALC 2.0-2? Can you provide the italc logfiles?

**Comment by spaceone** [comment]
If you are german you could also have a look at https://www.univention.de/produkte/ucsschool/ → The product UCS@school provides a stable release of iTALC and an own web based interface for the teacher console.

**Comment by joeknex** [comment]
Yes we are using 2.0.2, and no we are an English school

**Comment by spaceone** [comment]
The product also exists in english but all of the documentation currently not yet.

**Comment by joeknex** [comment]
We just want the normal iTALC program, and the main thing we would like fixed is the "Lock Student" button...

**Comment by Akswl** [comment]
I have the same problem for the crash of the master client. 

OS : Windows 7, 8.1 & 10

Maybe can i see in logs for tell you the problem ?

**Comment by rrignier** [comment]
I have also noticed random crashes on italc master. Or Linux italc clients. With upstream release.

**Comment by joeknex** [comment]
Any news? The "Lock Student" is the real big fix I need.. Thanks :)

**Comment by tobydox** [comment]
Can you please try https://github.com/iTALC/italc/releases/tag/v3.0.2.90 ? A completely new mechanism for blocking user input is now used and should work reliably on all Windows versions. Please note that this currently does not affect remote control. A fix to disable local user input here is still in progress.

**Comment by tobydox** [comment]
Please migrate to Veyon (http://veyon.io) which is the official successor of iTALC (which is discontinued). Since version 3.99.7 there's also an option to always enforce selected mode so computer gets locked after reboot again.
