### ISSUE TITLE
Lock Student

### ISSUE THREAD

**Issue by joeknex** [iTALC/italc#29]
"Lock Student" Does not work on Windows 7

**Comment by joeknex** [comment]
@tobydox This still does not work in the 3.0.0 release... or a way to do #30

**Comment by spaceone** [comment]
Hit me, too.

**Comment by tobydox** [comment]
Can you please try https://github.com/iTALC/italc/releases/tag/v3.0.2.90 ? A completely new mechanism for blocking user input is now used and should work reliably on all Windows versions.

**Comment by tobydox** [comment]
Issue should be fixed in v3.0.3.
