### ISSUE TITLE
authenticate messages changed into pop up

### ISSUE THREAD

**Issue by spaceone** [iTALC/italc#31]
![2016-07-21-175942_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1100188/17029826/2291a912-4f6d-11e6-99de-8abf5b53f580.png)
After upgrading to the latest version the unauthorized-access messages have changed into a pop up. This is very disturbing if this happens every second. The pop up should be changed into a singleton or shown again in the taskbar instead of a pop up.

**Comment by tobydox** [comment]
According to https://github.com/iTALC/italc/blob/italc3/ica/src/ItalcSlaveManager.cpp#L185 this only happens if system tray icon is hidden via configuration. I'll try to provide a fix nevertheless.

**Comment by tobydox** [comment]
FYI: related changes in italc3 branch have been backported to italc2 branch in order to stay compatible regarding the send message feature.
