### ISSUE TITLE
iTalc crashing

### ISSUE THREAD

**Issue by aksld** [iTALC/italc#35]
In the picture, italc crashed and have to restart every time ..

Since the version 2.02

Actually version 3

& thanks for the new version :+1: 

![italc_bug](https://cloud.githubusercontent.com/assets/6853619/17731677/9cdddd9c-646e-11e6-8de8-77228e74a094.png)

**Comment by tobydox** [comment]
When/under which circumstances does this happen? Are you using iTALC 3 on both master and client?

**Comment by tobydox** [comment]
Should be fixed in version 3.0.2 and newer.
