### ISSUE TITLE
Client service v3.0.0 fails to start after clean install on Win7,Win10

### ISSUE THREAD

**Issue by barik11** [iTALC/italc#36]
Client service v3.0.0 fails to start, even after clean install on Win7-32bit, and also on Win10-64bit.
This happens both when installed with/out the iTALC-Master option.
On same machines, the iTALC version 2.0.2 installation+operation works fine, for both client and teacher.
Attched:
[ica3-fails-to-start.zip](https://github.com/iTALC/italc/files/428705/ica3-fails-to-start.zip)

**Comment by tobydox** [comment]
Can you please try to stop the iTALC Service and start "ica.exe" manually in your session? Does this work? If so, can you please attach ItalcCoreServer.log?

**Comment by tobydox** [comment]
Can you please try with iTALC 3.0.1?

**Comment by tobydox** [comment]
Closing this due to missing feedback. Feel free to open a new bug report if this is still an issue for current versions of iTALC.
