### ISSUE TITLE
User names in Cyrillic

### ISSUE THREAD

**Issue by BabkaFox** [iTALC/italc#37]
We try to use your program at a university in Russia. Usernames our students are written in Russian. iTALC displays gibberish.
How to fix it?

Thank you for your work!

**Comment by tobydox** [comment]
Which version are you using? Did this work in previous versions? Which platform/operating system are you on?

**Comment by BabkaFox** [comment]
![cyrrilic_italc](https://cloud.githubusercontent.com/assets/6008648/18230673/f2559ad0-72ab-11e6-8e54-95b0715947e2.PNG)
iTALC 3.0.0
Platform is Windows enterprise x64

 iTALC v. 2.0.2 displays gibberish too.

**Comment by tobydox** [comment]
Please test https://www.tu-chemnitz.de/~doto/italc/italc-3.0.1-win64-setup.exe

**Comment by BabkaFox** [comment]
Thank you!
Everything is working

**Comment by tobydox** [comment]
I'm glad it's working - feel free to donate for this bugfix (1,5 hours of work) or the software in general ;-)
