### ISSUE TITLE
can not connect client

### ISSUE THREAD

**Issue by wufengyi** [iTALC/italc#38]
hi,

i am using italc master to live view one of my clients,in client i saw "can not auth itself" error message.
and below is the ita client log:

**11/09/2016 12:34:26 AM rfbProcessClientSecurityType: executing handler for type 40
Sun Sep 11 00:34:26 2016: [ERR] PublicDSAKey::load(): could not open file "/etc/italc/keys/public/teacher/key"
Sun Sep 11 00:34:26 2016: [ERR] DsaKey::verifySignature(): invalid key
Sun Sep 11 00:34:26 2016: [WARN] ItalcCoreServer::authSecTypeItalc(): failed authenticating client 45.79.130.167
11/09/2016 12:34:26 AM rfbClientSendString("Signature verification failed!")
11/09/2016 12:34:26 AM client_count: 0
11/09/2016 12:34:26 AM Client 45.79.130.167 gone
11/09/2016 12:34:26 AM Statistics             events    Transmit/ RawEquiv ( saved)
11/09/2016 12:34:26 AM  TOTALS              :      0 |         0/        0 (  0.0%)
11/09/2016 12:34:26 AM Statistics             events    Received/ RawEquiv ( saved)
11/09/2016 12:34:26 AM  TOTALS              :      0 |         0/        0 (  0.0%)**

anyone can help me with that?
thanks.

**Comment by tobydox** [comment]
You did not create/setup any authentication keys. Please use the iTALC Management Console (imc) to create/setup these.
