### ISSUE TITLE
Full screen demo

### ISSUE THREAD

**Issue by breeze833** [iTALC/italc#41]
Hi,

I compile and install italc3 on Ubuntu 16.04 with qt5.5.1. When starting a full screen demo, the students' desktops are not fully covered by the demo. The demo window is shifted down-right. Therefore the launch bar and title bars are visible. I am not sure whether this is due to a library version mismatch or not. However, I found a workaround for my environment.

At line 46 in ica/src/DemoClient.cpp, the window flags set by the parent LockWidget are overwritten at this point. To correct this, an if-statement can be used. When the fullscreen parameter is true, the Qt::X11BypassWindowManagerHint should be added to the list.

**Comment by izzyu91** [comment]
I have this issue under Windows (7, 8.1, 10). The window of the full screen demo also does not fully cover the screen but has title and launchbar visible. I can reproduce the issue by resetting my test VMs.
