### ISSUE TITLE
Windows 7 multi logon

### ISSUE THREAD

**Issue by Gilles514** [iTALC/italc#42]
Hi,
In my school, students of the same class have the same username and password.
Is it possible to open 32 windows 7 sessions on 32 computers with iTalc 3 as it was possible with older iTalc versions and Windows XP ?

Best regards,
Gilles

**Comment by tobydox** [comment]
Hi,

this is currently not possible as this feature has been removed in iTALC 2. There's no reliable mechanism that I'm aware of to make Windows log on a certain user with given credentials.

Best regards
Tobias

**Comment by joeknex** [comment]
@tobydox Hello, I know that NetSupport School http://www.netsupportschool.com/index.asp has multi logon. This is a fantastic program and something we have looked into getting...
