### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by micetto** [iTALC/italc#43]
Current version (from v3.0.0) reports the following error on submitting 'make install'

Scanning dependencies of target tr.qm
[  1%] Generating ../lib/resources/tr.qm
make[2]: execvp: ../lib/resources/tr.ts: Permission denied
CMakeFiles/tr.qm.dir/build.make:60: recipe for target '../lib/resources/tr.qm' failed
make[2]: *** [../lib/resources/tr.qm] Error 127
CMakeFiles/Makefile2:158: recipe for target 'CMakeFiles/tr.qm.dir/all' failed
make[1]: *** [CMakeFiles/tr.qm.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tobydox** [comment]
Please make sure to have Qt tools (such as lupdate and lrelease) installed. You should then be able to properly build iTALC.

**Comment by spaceone** [comment]
@tobydox Do you create the italc binaries on Ubuntu 14.04 or 16.04?
(There is no ppa:tobydox/mingw-x-xenial).
The debian package which is needed is qt5-linguist-tools (which provides the lupdate and lrelease binaries).

**Comment by spaceone** [comment]
If you cross-compile with mingw you need to install the package "qt5tools-mingw-w64" otherwise the package "qttools5-dev-tools" (http://packages.ubuntu.com/xenial/amd64/qttools5-dev-tools/filelist) is needed.

**Comment by jamj2000** [comment]
Are you running "make install" with root privileges?
