### ISSUE TITLE
Win64 demo mode problem

### ISSUE THREAD

**Issue by williwipp** [iTALC/italc#44]
Hi,
first of all - nice software !

I have a problem with the demo mode (windows or fullscreen) in win64.
Everything else is working fine but when I start the demo mode the clients keep hanging in "Verbindung zu ip.ip.ip.ip:11400 wir hergestellt" (where ip.ip.ip.ip is the ip adress of the master).
I tried both possible "demo server" but the result is the same 
any ideas ?
Ohh sorry I forgot:
It is running on 2 win 7 Professionell 64

**Comment by tobydox** [comment]
Please upgrade to iTALC 3.0.0 where this issue is fixed.

**Comment by williwipp** [comment]
Sorry forgot to say, that I am already on 3.0.0
