### ISSUE TITLE
how can i edit source core

### ISSUE THREAD

**Issue by arun31cs12** [iTALC/italc#46]
hi friends plz tell how can i edit itacl source cord

**Comment by tobydox** [comment]
You can clone the git repository to your computer and start editing the source code locally. If you want to contribute changes, commit them and send a pull request so we can review and eventually merge it.

**Comment by arun31cs12** [comment]
i am useing for windows 8.1 how can i edit git repository my pc

**Comment by tobydox** [comment]
https://www.google.de/#q=howto+use+git+windows
