### ISSUE TITLE
Make Error (Spanish/English)

### ISSUE THREAD

**Issue by Ansaro** [iTALC/italc#49]
[  0%] Generating ../lib/resources/pt_pt.qm
make[2]: execvp: ../lib/resources/pt_pt.ts: Permiso denegado
CMakeFiles/pt_pt.qm.dir/build.make:60: fallo en las instrucciones para el objetivo '../lib/resources/pt_pt.qm'
make[2]: *** [../lib/resources/pt_pt.qm] Error 127
CMakeFiles/Makefile2:158: fallo en las instrucciones para el objetivo 'CMakeFiles/pt_pt.qm.dir/all'
make[1]: *** [CMakeFiles/pt_pt.qm.dir/all] Error 2
Makefile:149: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
----------------------------------------------------------------------------------------------------------------------------------
[  0%] Generating ../lib/resources/pt_pt.qm
make[2]: execvp: ../lib/resources/pt_pt.ts: Permission denied
CMakeFiles/pt_pt.qm.dir/build.make:60: failure in the instructions for the target '../lib/resources/pt_pt.qm'
make[2]: *** [../lib/resources/pt_pt.qm] Error 127
CMakeFiles/Makefile2:158: failure in the instructions for the target 'CMakeFiles/pt_pt.qm.dir/all'
make[1]: *** [CMakeFiles/pt_pt.qm.dir/all] Error 2
Makefile:149: failure in the instructions for the target 'all'
make: *** [all] Error 2

**Comment by spaceone** [comment]
This is the same as https://github.com/iTALC/italc/issues/43

**Comment by Ansaro** [comment]
I have fallow the instruction of #43  but that's mystake  still there I even installed the ubuntu 16.04 the qt4-dev-tools packet

**Comment by Ansaro** [comment]
I have fallow the instruction of #43 but that's mystake still there I even installed the ubuntu 16.04 the qt4-dev-tools packet

**Comment by spaceone** [comment]
Me, too.

**Comment by spaceone** [comment]
Try installing the QT5 package! "qt5-dev-tools"

**Comment by spaceone** [comment]
If you cross-compile with mingw you need to install the package "qt5tools-mingw-w64" otherwise the package "qttools5-dev-tools" (http://packages.ubuntu.com/xenial/amd64/qttools5-dev-tools/filelist) is needed.

**Comment by jamj2000** [comment]
Estás ejecutando "make install" con permisos de root?

Are you running "make install" with root privileges?
