### ISSUE TITLE
How to change the interface language

### ISSUE THREAD

**Issue by gogoout** [iTALC/italc#55]
I'm currently using iTALC under window. How can I change the interface language? Every time I changed language in setting, it will switch back to "system default". Also what file should I edit to make a new language? 
The link offered in the office website is broken. http://italc.sourceforge.net/wiki/index.php?title=Creating_a_localization

Thanks for this great software.

**Comment by tobydox** [comment]
Thank you very much for your bug report! I'll have a look at the issue.

I just updated the instructions for contributing to the iTALC translations: https://github.com/iTALC/italc/wiki/Creating-or-improving-translations

**Comment by tobydox** [comment]
I just implemented UI language configuration in the iTALC Management Console which applies for all program components (master and service). The functionless language selector has been removed from the master component. Can you please test the attached test build?
[italc-3.0.2-win32.zip](https://github.com/iTALC/italc/files/605780/italc-3.0.2-win32.zip)

**Comment by gogoout** [comment]
Thanks for the quick respond.
I've tested the build, there is still some problem.

1. My system default language is chinese but in iTALC the language is Arabic.
2. When I change the UI language the Management Console will have a chance to crash , otherwise it will keep blur from the console until I manually close the window.
3. Changning to chinese(both Simplified and Traditional) seems to have no effect, the ui (in console and master) will become english. Other language (I have tested only Arabic and French) is OK.

**Comment by tobydox** [comment]
Thank you very much for testing! I improved the language configuration internally so it should work now properly for Chinese and other languages. Please test the attached installer.
[italc-3.0.2-win32.zip](https://github.com/iTALC/italc/files/609401/italc-3.0.2-win32.zip)

**Comment by gogoout** [comment]
Yes it worked like a charm. Thanks, I'm going to close this issue or shall we close this after release?

**Comment by tobydox** [comment]
I'm glad it works :-) I hope I can release 3.0.2 in the mid of December.
