### ISSUE TITLE
I can not show my desktop to the students

### ISSUE THREAD

**Issue by cavoloneso** [iTALC/italc#56]
Good morning.
I can observe and control all PC in the lan, but I can not show my desktop to the students. I can not understand the log file.
Could you help me?

**Comment by cavoloneso** [comment]
I can not upload file log...grrrr

**Comment by spaceone** [comment]
You can. you have to rename it to logfile.txt

**Comment by cavoloneso** [comment]
I did what you suggested.
The first file had like extention  ".xml" (it was logfile.xml).
The other two files had like extention ".log"
Can someone help me please?

[logfile.txt](https://github.com/iTALC/italc/files/597853/logfile.txt)
[ItalcCoreServer.txt](https://github.com/iTALC/italc/files/597857/ItalcCoreServer.txt)
[ItalcServiceMonitor.txt](https://github.com/iTALC/italc/files/597858/ItalcServiceMonitor.txt)

**Comment by cavoloneso** [comment]
;)...... 
Nobody can help me

**Comment by tobydox** [comment]
There seems to be a general problem with the service and user sessions. The reason for that is that iTALC 3 does not support Windows XP anymore so please upgrade to a recent (vendor-supported) operating system such as Windows 7 or Debian 8/Ubuntu Linux 14.04/16.04. I'm sorry that I can't give any further help in your case.
