### ISSUE TITLE
Do not pass the authentication on Windows XP Home

### ISSUE THREAD

**Issue by mrkaban** [iTALC/italc#57]
Hello, sorry for the stupid question. In general, trying to adjust iTals 3.0.1 on two computers. One on Windows XP Pro, on it all works fine. The second computer to Windows XP Home Edition, and it could not adjust. In the management console, in the Authentication tab in the input setting unit in the system, managing permissions have the user name "User2,", continue to push the test, I enter the correct password, and the error takes off "When passing the authentication credentials any errors!". Tell me please, what is connected with an error? can you fix it?

I have the impression that this is just the difference between the versions of Windows Xp.

I also want to express my gratitude for such a cool program! She added to my site, and on it I wrote a long article by its setting - [link](http://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B-%D1%81%D0%BF%D0%BE/%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B5-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B5-italc.html).

**Comment by mrkaban** [comment]
I note that even tried the old version 2.0.2. Computer Name in English.

Keys created and imported.

**Comment by tobydox** [comment]
First of all please note that Windows XP is not supported by iTALC any longer, as it is not supported by Microsoft in general anymore. It's possible that logon authentication does not work on Home Edition due to missing domain functionality. Please try to setup the key authentication which should always work.
