### ISSUE TITLE
Full Screen Demo mode in v.3.0.1 is working just fine but...

### ISSUE THREAD

**Issue by minekanichael** [iTALC/italc#61]
Full Screen Demo mode disables the mouse and keyboard but when the screen is minimize, the client will have access to mouse and keyboard and can't go back to the iTALC demo. Perhaps you can disable the minimize button when in full screen demo? Maximize button works just fine since the display sometimes doesn't cover the screen entirely.

Thank you very much.

**Comment by tobydox** [comment]
Can you please try https://github.com/iTALC/italc/releases/tag/v3.0.2.90 ? A completely new mechanism for blocking user input is now used and should work reliably on all Windows versions.

**Comment by tobydox** [comment]
Closing due to missing feedback.
