### ISSUE TITLE
Snapshot of all client pcs

### ISSUE THREAD

**Issue by Sightt** [iTALC/italc#63]
Is it possible to take a snapshot of all the client machines at the same time?  Also it would be nice to be able to take a snapshot evry 3 or 5 seconds do not need full video recording.  A great way to monitor tests and quizzes.  if this is not possible now can it be added in a near future release?

**Comment by jamj2000** [comment]
You could use a screenshot app. 

For Windows, autoscreen: https://sourceforge.net/projects/autoscreen/.

**Comment by tobydox** [comment]
You can try Veyon 4, the successor of iTALC (https://github.com/veyon/veyon/releases) which supports taking snapshots of all computers at the same time.
