### ISSUE TITLE
"Power on" (Wake-on-Lan) does not work on Linux Mint 17 Cinnamon

### ISSUE THREAD

**Issue by sraps** [iTALC/italc#7]
Hello,
trying to set up a test setup of iTALC, which is great. It needs some tuning but seems to be workable with most features, except Wake-on-lan.

In short: I have traced down the problem to that the magicpacket is not being sent from iTALC.

Elaborated:
1. Wake-on-lan on is enabled and working on the target machine - tested with etherwake, target machine powers up successfully. It works even without specifying interface ("i" option of etherwake).
2. MagicPacket is not being sent by iTalc, tested with tcpdump.
3. When testing WoL using etherwake, MagicPacket is being sent and being successfully captured by tcpdump.
4. ica on a teacher's machine is being run with root privileges. As I understand that it is not possible to sent MagicPacket without elevated privileges.
5. Tested italc process using both, ordinary and elevated privileges.
6. Currently (as it is test setup) target machine is connected using crossover cable. But it does not influence anything, ref. Nr.1.
7. Dug iTALC ica code to the method (broadcastWOLPacket) responsible to send MagicPackets. Saw that obviously some time ago there has been etherwake used to send the packet, then switched to current algorithm, commenting out etherwake spawn.
8. Would like to add that tested using wakeonlan command line tool, which does not send MP, although it states it does. tcpdump captures nothing. Target machine does not react.
9. dmesg shows no problem neither pressing "power on" button in iTALC, nor otherwise.
10. ica and italc stderror says nothing suspicious.
11. while italc running tcpdump logs continuous ARP requests "Request who-has <target IP goes here>"
12. iTALC version from repository (2.0.1-4ubuntu0.14.04.1 0)
13. teacher's machine Linux Mint 17 64b

Thanks for the great job!

**Comment by tobydox** [comment]
Please migrate to Veyon (http://veyon.io) - iTALC is not supported any longer. Feel free to test and open/copy issue if this still doesn't work for you.
