### ISSUE TITLE
Not authenticating with Windows 10 Pro 64 bit

### ISSUE THREAD

**Issue by Fandeboris** [iTALC/italc#70]
Using Italc 3.0.1. Have classroom with 30 seats, 2 seats fail authentication. Have deleted Registry Keys and re-installed with same effect.
enclosed is registry  copy
[ITALC.txt](https://github.com/iTALC/italc/files/635169/ITALC.txt)

**Comment by tobydox** [comment]
The configuration indicates that you enabled key authentication. Did you setup the authentication keys on master and clients? If not, try to disable key authentication and use logon authentication only.

**Comment by Fandeboris** [comment]
Thanks for the reply!
Key Authentication was never turned on or used or even setup. Students log in with a 'user' account and iTalc was installed using an administrative account. 
The other 30 seats were installed by logging in using the student account and selecting "Run as Administrator" 
I deleted the original and re-installed using the process of the other 30 machines, but apparently there are still pieces still left from the original install. 
Since I have an image of the machine; R&R  (Reformat and Re-install) is not a problem.  We are winding down for the term, time is not an issue. 
Thanks

**Comment by tobydox** [comment]
Please use the iTALC Management Console to setup logon authentication (exclusively!) on both master and clients and make sure to setup the logon authentication ACLs properly (i.e. allow the group "teacher" to access) on *all* computers *identically*.

**Comment by tobydox** [comment]
If this is still an issue, please respond within 7 days, otherwise I'll close this issue.

**Comment by Fandeboris** [comment]
Due to the holidays and buildings being closed, I have had limited access to the Lab. All the settings in the control panel indicated it was not activated.

I have tried to uninstall and re-install, but the results are the same.  I went through the registry and removed all the keys I could find and tried again. Same results.

If there is something else I need to do, I would appreciate knowing.  My next effort is to reformat and re-install the operating system.


I do appreciate your help in this. What is so confusing is the fact that there are 28 more machines in the Lab, identical to the one giving trouble, and they work perfectly.


Thanks


________________________________

**Comment by Fandeboris** [comment]
Due to the holidays and buildings being closed, I have had limited access to the Lab. All the settings in the control panel indicated it was not activated.

I have tried to uninstall and re-install, but the results are the same.  I went through the registry and removed all the keys I could find and tried again. Same results.

If there is something else I need to do, I would appreciate knowing.  My next effort is to reformat and re-install the operating system.


I do appreciate your help in this. What is so confusing is the fact that there are 28 more machines in the Lab, identical to the one giving trouble, and they work perfectly.


Thanks

Fan

________________________________

**Comment by googleman26** [comment]
Hi! Fandeboris

i am new here but i have used italc 2 years ago..maybe i can help you or i can suggest what i have done using italc..

try using italc 3.0.2.90

A little bit background in our laboratories.

i have 33 pc's on a lab.. 32 pcs are student and 1 is the instructor which is the italc server

i have to users on 33 pcs i have..first administrator and italc users. 
Then italc user have the same password in all 33 pc's. 
next proceed on installing italc on each computer. 
after that, on italc management console on "italc server tab" at demo server select "vnc reflector" i have provided print screen..below
![italc server](https://cloud.githubusercontent.com/assets/25044145/21829600/106b6276-d7d2-11e6-8ee9-785fe593cebf.png)


next to that, under " authentication tab" click "test" like what i have provided print screen below
![test](https://cloud.githubusercontent.com/assets/25044145/21829599/106b340e-d7d2-11e6-994d-397a5b1c3088.png)

the result should be successfully  
![success](https://cloud.githubusercontent.com/assets/25044145/21829742/f4563bfa-d7d2-11e6-81e3-7c2cb32a8e6a.png)

reminder:

 first, u have default administrator account.
then, for italc  account i used for example " italc" that is the user account..all 33 pc's must have this account.

then on each student account you must have to test each user "italc" and the password  you used to authenticate.. then all your student can be viewed on the italc server..

Thanks.. please try this.. here at our laboratory it is working.

**Comment by tobydox** [comment]
Please migrate to Veyon (http://veyon.io) - iTALC is not supported any longer.
