### ISSUE TITLE
Any user who has his screen blocked can press Ctrl+alt+supr and end the blocking task recovering access to his pc

### ISSUE THREAD

**Issue by Ambro17** [iTALC/italc#73]
I'm testing the program on several PCs Windows 7 32 bits Acer AIOs and i found this problem. Many users won't even try to do it, but the few who know some basic task management could regain access to their PCs. The iTALc management console doesn't refresh to the now "unlocked" state so you can't know whether it's blocked or not.
Maybe it's an easy fix.. maybe it's not necessary but i think it's worth mentioning.

I attach a screenshot taken from master machine, observing while i succesfully recover access from client app.
![access](https://cloud.githubusercontent.com/assets/11272260/21185023/c6fb517c-c1ed-11e6-81f9-b02be673ca40.png)

**Comment by tobydox** [comment]
Can you please try https://github.com/iTALC/italc/releases/tag/v3.0.2.90 ? A completely new mechanism for blocking user input is now used and should work reliably on all Windows versions.

**Comment by tobydox** [comment]
Issue is fixed in v3.0.3.
