### ISSUE TITLE
Can't Lock student mouse and keyboard

### ISSUE THREAD

**Issue by Cocolas44** [iTALC/italc#85]
Hello,
First of all, good job! iTalc is a fantastic software.

I'm testing iTalc 3.0.3 and when I try to use "Block student" the mouse and keyboard still work. "Display block" work but they just have to use Alt+Tab to pass over.
Thanks for your help,
Nicolas

**Comment by ZethFrost** [comment]
The only way to actually succeed in getting rid of that problem is like running a "refresh" piece of code that will bring the lock screen up ever second or something.

Also block out Alt + tab, CTL ALT DEL, and also Win + R and Win +E.

**Comment by lbssousa** [comment]
With Epoptes (Linux only), one can grab client's local user input while assisting it by passing options `-grabkbd` and `-grabptr` to client's x11vnc instance. However, although keyboard is properly grabbed, currently x11vnc can only grab the mouse buttons, but not the pointer movement (i.e., client user can not click the buttons, but it still can move the pointer).

I can circumvent this limitation with a wrapper script around x11vnc that slows down pointer acceleration by a huge rate, via xinput, while client's computer gets assisted. You can see this wrapper [here](http://bazaar.launchpad.net/~oiteam/epoptes/x11vnc-wrapper-with-alt-input-grabbing/view/head:/epoptes-client/x11vnc-wrapper).

**Comment by Cocolas44** [comment]
> running a "refresh" piece of code that will bring the lock screen up ever second or something.
Good idea, I know how to do that with AutoIt but not in C++...

**Comment by tobydox** [comment]
Please migrate to Veyon, the successor of iTALC, which has a rewritten and reliable screen lock feature :-)
