### ISSUE TITLE
italc 3.03 overview not functional

### ISSUE THREAD

**Issue by Brusok** [iTALC/italc#89]
italc 3.03 overview mode not functional on WIn10 64bit. Worked well on italc 2. Re-installation does not solve problem.

**Comment by tobydox** [comment]
Hi,

please switch to Veyon (http://veyon.io) which is the official successor of iTALC and has a completely rewritten core. Probably your issue will be fixed already :-)

Best regards

Tobias

**Comment by Brusok** [comment]
Thanks!
