### ISSUE TITLE
Presentation mode doesn't work in iTALC 2.0-2

### ISSUE THREAD

**Issue by spaceone** [iTALC/italc#9]
With iTALC 2.0-2 the presentation mode doesn't work anymore.
I have a lot of mixed clients using Win XP, 7, 8, 8.1.
One client displays a clock symbol and tries to connect to the VPN port but the connection never establishes. Every other client does just nothing.
Any idea which commit might have caused this regression?

**Comment by spaceone** [comment]
Are there API changes in the protocol or the data which are exchanged between client and master between iTALC 2.0.0, 2.0.1 and 2.0.2? Should these versions work together?

**Comment by spaceone** [comment]
It's already not working with iTALC 2.0.1.

**Comment by Saenn** [comment]
Hi

You can to change the VNC server to demo server in italc configuration. But for me it's working one time and the problem come back.

Italc isn't working  nice in  Win 7/8/10.

Maybe i'll try to update it .. But it's working with Qt 4, now it's 5.x !

**Comment by spaceone** [comment]
Hm, is this a QT issue? I think it has more to do with VPN. It looks like the demo-server doesn't accept VPN connections.

**Comment by spaceone** [comment]
In all my installations the Demoserver-Backend is "VNC-Reflector".

**Comment by barteekelder** [comment]
Indeed the demo mode doesn't work, I got it set on "iTALC 1 demo server" now but it had no effect so I went on searching for the problem but it seems like iTALC just picks a random port for the Demo server and not the default port: 11400. When I restart iTALC it uses the right core port 11100 but the Demo port is diffrent every time!

**Comment by spaceone** [comment]
Oh, that's a nice information! You restart iTALC on the client side? Or on the server side?

**Comment by barteekelder** [comment]
On The server side.

**Comment by spaceone** [comment]
Could it be that the systems are using IPv6? In the code I can see some splitting at ':' which would fail for a IPv6 address.

**Comment by spaceone** [comment]
Maybe this helps? https://github.com/spaceone/italc/commit/894cb9930030fd60ab2492b933cc42c9ba1423cf
(I currently have no italc setup to test it)

**Comment by IR4T4** [comment]
Hi, 
I did some testing with wireshark today and to me the basic problem seems to be the client update process itself. 
I can confirm the source port of packets changes but that shouldn't matter because the destination port is always 11400. The traffic itself on port 11400 seems rare while 11100 is busy all the time.

I'll do some deeper testing soon - let's nail this issue down.

**Comment by spaceone** [comment]
This has been fixed by https://github.com/iTALC/italc/commit/ec3e5afe3194fcd99b498b73c59ad15c44ea4bcf

**Comment by zifnab69** [comment]
Hello
how do you solve the problem ?
thank you

**Comment by spaceone** [comment]
@zifnab69 Just use the latest iTALC 3 version

**Comment by zifnab69** [comment]
i use italc 3.3 and the demo mode don't work
i just start with this software.
i can see the student screen, but student can't see the demo

**Comment by zifnab69** [comment]
ok. it work now. i changed from italc server to vnc reflector and it's ok.
what is the difference between both ?
thank you
