### ISSUE TITLE
Send Ctrl Alt Del

### ISSUE THREAD

**Issue by gregfink83** [iTALC/italc#90]
Is there anyway to send ctrl alt del to a remote computer?  After taking control I can't login to the remote computer without the ability to press ctrl alt del.  I've tried ctrl alt ins and ctrl alt end.

Thanks for your help.

**Comment by mdmorris05** [comment]
The only way i do it is turn on onscreen keyboard with the mouse!

**Comment by tobydox** [comment]
This has been implemented in 870fb5fbe0cdac713d494445a0365d0f7a974692 and ce31c28a7b79d11392037580de42b796bf8df8cd and will be available in alpha release of iTALC/Veyon 4 in a few days.
