### ISSUE TITLE
iTALC and existing VNC installation

### ISSUE THREAD

**Issue by eleftrik** [iTALC/italc#93]
I have several Windows (from XP to 10) PCs joining a domain, running **UltraVNC** on standard ports, with OS authentication enabled.
If I install iTALC (tried 3.0.3) on these computers, UltraVNC service becomes unreachable (I can't connect to them via VNC Viewer).
Is there any iTALC options to tweak? I couldn't find it.
Thank you

**Comment by tobydox** [comment]
With Veyon 3.99.6 and newer you can use the existing VNC server installation instead of the builtin VNC server (which is based on UltraVNC and thus clashes with other UltraVNC instances).
