### ISSUE TITLE
iTALC 3.0.3 Conect Problem

### ISSUE THREAD

**Issue by AssafSneh** [iTALC/italc#94]
Thanks God!

Hii, nice to meet you.
i realy love you italc software.
i want to give you 100$ for it.
but first i need it to work.
i do all what i need like you show here:
https://www.youtube.com/watch?v=OnM0cCGtVdI
and i get "Position offline" messege.

you can see my settings are good!
why i don`t get screen?
i use in this software: Employee Desktop Live Viewer and i get signal to see the other computer.
in your software i use in teacher computer with windows 10 and with student in windows 7.

Hope to here from you soon.
My phone is +972-58-678-4545

Please contact me dear.

Regards,
Assaf Sneh.

**Comment by tobydox** [comment]
Please migrate to Veyon (http://veyon.io) and refer to the troubleshooting section in the administration manual in case of problems.
