### ISSUE TITLE
where can i get some files?

### ISSUE THREAD

**Issue by saboten1101** [iTALC/italc#97]
Can someone help me?

I did cmake, but cmake said my env does not have some files....

-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads - not found
-- Looking for include file process.h - not found
-- Looking for include file vfork.h - not found
-- Looking for include file linux/videodev.h - not found
-- Looking for include file ws2tcpip.h - not found
-- Looking for XReadScreen - not found
-- Looking for FBPMForceLevel - not found
-- Looking for include file X11/extensions/readdisplay.h - not found

Where can I get those files??

thanks..

**Comment by tobydox** [comment]
Please install the dependencies as described in https://github.com/iTALC/italc/blob/master/INSTALL. In Your case several packages are missing.
