### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by izzyu91** [iTALC/italc#98]
Hi,

I tried looking for a up-to-date documentation or manual on iTalc but couldn't find one. The Wiki on SourceForge seems to be totally dead (meaning there is only one page called "Home"). The PDF file linked on the website is from 2007 (Version 1.0.4)

Is there an up-to-date documentation or a wiki somewhere out there?

Any help would be greatly appreciated.

**Comment by tobydox** [comment]
Please migrate to Veyon (http://veyon.io) and refer to the documentation linked at the website :-)
